<a href="https://colab.research.google.com/github/mkh2097/CI_Text_Recognition/blob/main/SKlearn_Final_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install hazm

     |████████████████████████████████| 317kB 4.2MB/s 
     |████████████████████████████████| 235kB 16.0MB/s 
     |████████████████████████████████| 1.4MB 23.0MB/s 
  Created wheel for libwapiti: filename=libwapiti-0.2.1-cp36-cp36m-linux_x86_64.whl size=154294 sha256=12fe9912cfb4a6de2f456a0fd205cd0a6f3891a48def0866c7e2b76a69e14474
  Stored in directory: /root/.cache/pip/wheels/66/15/54/4510dce8bb958b1cdd2c47425cbd1e1eecc0480ac9bb1fb9ab
  Created wheel for nltk: filename=nltk-3.3-cp36-none-any.whl size=1394467 sha256=c6b57277e4743f436234053c78040323e7495a11aa699c5f2695473de8502a24
  Stored in directory: /root/.cache/pip/wheels/d1/ab/40/3bceea46922767e42986aef7606a600538ca80de6062dc266c
Successfully built libwapiti nltk
  Found existing installation: nltk 3.2.5
    Uninstalling nltk-3.2.5:
      Successfully uninstalled nltk-3.2.5


In [ ]:
import numpy as np
import pandas as pd
import re
import nltk
from sklearn.datasets import load_files
nltk.download('stopwords')
import pickle
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/train.csv')
df_test = pd.read_csv('/content/drive/MyDrive/test.csv.zip')

In [ ]:
X, Y = df.Text, df.Category

In [ ]:
# lineList = list()
# with open('stop_words.txt') as f:
#   for line in f:
#     lineList.append(line)

# lineList = [x.strip() for x in lineList] 

In [ ]:
df_test

Id                                               Text
0          0  \nهفت اقليم \nآلودگي هوا پكن را تهديد مي كند \...
1          1  \nگل و گياه زعفران زينتي \nنام علمي: Crocus ba...
2          2  \nيادداشت \nقانون بودجه و صنايع كوچك \nدر شمار...
3          3  \nدر سالروز ميلاد حضرت مهدي \nهمايش ادبي دانش ...
4          4  \nاز IRA تا فارك \n بوگوتا، پايتخت پرهرج ومرج ...
...      ...                                                ...
16673  16673  \nبراي ارتقاي كيفيت در بخش آموزش عالي \nوزارت ...
16674  16674  \nديدار رهبر انقلاب اسلامي با \nگروهي از جوانا...
16675  16675  \nبحران در دولت ائتلافي هند \nانشعاب در حزب اي...
16676  16676  \nچرا به آثار باستاني خود خنجر؟ مي زنيم! \nآنط...
16677  16677  \nيك استاد دانشگاه: قاچاق كالا ناشي ازضعف \nتو...

[16678 rows x 2 columns]

In [ ]:
# from __future__ import unicode_literals
# from hazm import *
# import re, string

# def remove_stopwords(text):
#     text = [word for word in text.split() if word not in lineList]
#     return " ".join(text)

# normalizer = Normalizer()


# special = re.compile(r'\W')
# single = re.compile(r'\s+', flags=re.I)

# number = re.compile(r"[-+]?[0-9]+")
# pnumber = re.compile(r"[-+][\u06F0-\u06F90-9]+")
# url = re.compile(r"https?://\S+|www\.\S+")
# html = re.compile(r"<.*?>")
# emoji_pattern = re.compile(
#     "["
#     u"\U0001F600-\U0001F64F"  # emoticons
#     u"\U0001F300-\U0001F5FF"  # symbols & pictographs
#     u"\U0001F680-\U0001F6FF"  # transport & map symbols
#     u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
#     u"\U00002702-\U000027B0"
#     u"\U000024C2-\U0001F251"
#     "]+",
#     flags=re.UNICODE,
# )


# # df["Text"] = df.Text.map(remove_stopwords)
# # df["Text"] = df.Text.map(lambda x: url.sub(r" ",x))
# # df["Text"] = df.Text.map(lambda x: html.sub(r" ",x))
# # df["Text"] = df.Text.map(lambda x: emoji_pattern.sub(r" ",x))
# # df["Text"] = df.Text.map(lambda x: number.sub(r" ",x))
# # df["Text"] = df.Text.map(lambda x: pnumber.sub(r" ",x))
# df["Text"] = df.Text.map(lambda x: x.translate(str.maketrans(" ", " ", string.punctuation)))
# df["Text"] = df.Text.map(lambda x: special.sub(r" ",x))
# df["Text"] = df.Text.map(lambda x: single.sub(r" ", x))
# # df["Text"] = df.Text.map(lambda x: normalizer.normalize(x))


# # df_test["Text"] = df_test.Text.map(remove_stopwords)
# # df_test["Text"] = df_test.Text.map(lambda x: url.sub(r" ",x))
# # df_test["Text"] = df_test.Text.map(lambda x: html.sub(r" ",x))
# # df_test["Text"] = df_test.Text.map(lambda x: emoji_pattern.sub(r" ",x))
# # df_test["Text"] = df_test.Text.map(lambda x: number.sub(r" ",x))
# # df_test["Text"] = df_test.Text.map(lambda x: pnumber.sub(r" ",x))
# df_test["Text"] = df_test.Text.map(lambda x: x.translate(str.maketrans(" ", " ", string.punctuation)))
# df_test["Text"] = df_test.Text.map(lambda x: special.sub(r" ",x))
# df_test["Text"] = df_test.Text.map(lambda x: single.sub(r" ", x))
# # df_test["Text"] = df_test.Text.map(lambda x: normalizer.normalize(x))


# # for i in range(df_texts_size):
# #   bound = len(df_texts_hazm[i].split(' ')) - 1
# #   for char in "0123456789۰۱۲۳۴۵۶۷۸۹!#$%&().*+,،-/:;<=>?@[\\]^_`{|}~\t\n":
# #     df_texts_hazm[i] = df_texts_hazm[i].replace(char, ' ', bound)
# #   # for word in lineList:
# #   #   df_texts_hazm[i] = df_texts_hazm[i].replace(word, ' ', bound)


#   # df_texts_hazm[i] = url.sub(r"",df_texts_hazm[i])
#   # df_texts_hazm[i] = html.sub(r"",df_texts_hazm[i])
#   # df_texts_hazm[i] = emoji_pattern.sub(r"",df_texts_hazm[i])


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Text, df.Category, test_size=0.1, random_state=42)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
# tfidfconverter = TfidfVectorizer(max_features=1500, min_df=3, max_df=0.8)
tfidfconverter = TfidfVectorizer()

X = tfidfconverter.fit_transform(X_train)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.svm import LinearSVC, LinearSVR
from sklearn.svm import SVC, NuSVC
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.multiclass import OneVsRestClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import PassiveAggressiveClassifier


# parameters = {'clf__alpha': 0.01, 'tfidf__use_idf': True, 'vect__ngram_range': (1, 2)}

# classifier = GaussianNB()
# classifier = GridSearchCV(classifier, parameters, n_jobs=-1)
# classifier = RandomForestClassifier(n_estimators=200, random_state=0)
# classifier = RandomForestClassifier(n_estimators=100, criterion='gini',max_depth=10, random_state=0, max_features=None)
# classifier_sgc = SGDClassifier(loss="modified_huber", penalty="l2", max_iter=5000)

# classifier_linsvc = SVC(kernel='linear',probability=True)
# classifier_logreg = LogisticRegression(max_iter=1000)
# classifier = KNeighborsClassifier(n_neighbors = 3)
# classifier = SVC()
# classifier = OneVsRestClassifier(SVC(), n_jobs=-1)
# classifier = XGBClassifier()
# classifier = LinearSVC(loss="hinge", max_iter=10000, C=3)


# classifier = NuSVC(probability=True)
# classifier = LinearDiscriminantAnalysis()

# classifier_sgc.fit(X, y_train) 
# classifier_linsvc.fit(X, y_train) 
# classifier_logreg.fit(X, y_train) 

# estimators=[('sgc', classifier_sgc), ('svc', classifier_linsvc)]

# classifier = VotingClassifier(estimators, voting='hard', n_jobs=-1)

# classifier = classifier_sgc 

# classifier = NBSVM(C=0.001)

# classifier.fit(X, y_train) 

# classifier = PassiveAggressiveClassifier()

# pipe = Pipeline(steps = [("tfidf_vectorization", TfidfVectorizer()), ("classifier", MultinomialNB())])

# search_space = [{"classifier": [MultinomialNB()]}, 
#                 {"classifier": [LinearSVC()]},
#                 {"classifier": [PassiveAggressiveClassifier()]}, 
#                 {"classifier": [LogisticRegression()], 
#                 "classifier__solver": ["liblinear"]},
#                 {"classifier": [KNeighborsClassifier()],
#                  "classifier__n_neighbors": [6,7,8]}]

# classifier = GridSearchCV(estimator=pipe, param_grid=search_space, cv=10, return_train_score=True, n_jobs=-1, refit="AUC")                


#Two Best Models:
classifier = SGDClassifier(loss="modified_huber", max_iter=100000, alpha=0.00001)
# classifier = LinearSVC()

classifier.fit(X, y_train) 

SGDClassifier(alpha=1e-05, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='modified_huber',
              max_iter=100000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [ ]:
X = tfidfconverter.transform(X_test)
y_pred = classifier.predict(X)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[1568    5    2 ...    2    0    0]
 [  15   20    0 ...    0    0    0]
 [  41    1   27 ...    0    0    1]
 ...
 [   2    0    0 ... 1437    0    0]
 [   0    0    0 ...   16    4    0]
 [   4    0    0 ...    1    0   15]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                                                                      precision    recall  f1-score   support

                                                             Economy       0.79      0.89      0.83      1767
                                                 Economy.Agriculture       0.74      0.47      0.57        43
                                             Economy.Bank and Bourse       0.84      0.32      0.46        85
                                                    Economy.Commerce       0.67      0.06      0.11        33
                                   Economy.Dwelling and Construction       0.00      0.00      0.00         4
                                                    Economy.Industry       0.31      0.14      0.19        86
                                                         Economy.Oil       0.84      0.69      0.76       108
                                                  Literature and Art       0.63      0.65      0.64       450
         

In [ ]:
X = tfidfconverter.transform(df_test.Text)
Y_final = classifier.predict(X)
df_test_res = df_test.copy()
df_test_res.Text = Y_final
df_test_res = df_test_res.rename(columns = {"Text":"Category"}) 
df_test_res.to_csv("Final.csv", index=False)

In [ ]:
with open('text_classifier', 'wb') as picklefile:
    pickle.dump(classifier,picklefile)

In [ ]:
!ls

drive  Final.csv  sample_data  text_classifier
